name: Chunker
version: 1.21
main: main.Chunker
author: Go0fy_Go0ber
description: Async Minecraft world pre-generator
api-version: 1.20
commands:
  pregen:
    description: Enable pre-generation with customizable parameters
    permission: chunker.pregen
    usage: /pregen <ParallelTasksMultiplier> <PrintUpdateDelayin(Seconds/Minutes/Hours)> <world> <Radiusin(Blocks/Chunks/Regions) or default>
  pregenoff:
    description: Disable pre-generation
    permission: chunker.pregenoff
    usage: /pregenoff
permissions:
  chunker.pregen:
    description: Grants permission to use the pre-generation command with customizable parameters
    default: op
  chunker.pregenoff:
    description: Grants permission to disable pre-generation using the /pregenoff command
    default: op
  chunker.*:
    description: Provides access to all Chunker commands
    default: op
    children:
      chunker.pregen: true
      chunker.pregenoff: true